name: Deploy to Ubuntu Server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to server
        run: ssh root@134.209.146.138 -o StrictHostKeyChecking=no "cd /var/www/html/codeholic_product/streamlit-example && git pull"

